behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 5000
      buffer_size: 25000
      learning_rate: 0.0005
      beta: 0.004
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 2048
      num_layers: 12
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 50000
      swap_steps: 1000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
