default_settings: null
behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.0005
      beta: 0.01
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 1000000 
    network_settings:
      normalize: false
      hidden_units: 1024
      num_layers: 4
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.975
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 2
    even_checkpoints: false
    max_steps: 3000000000
    time_horizon: 1000
    summary_freq: 100000
    threaded: false
    self_play:
      save_steps: 50000
      team_change: 350000
      swap_steps: 2000
      window: 50
      play_against_latest_model_ratio: 0.7
      initial_elo: 1200.0
    behavioral_cloning: null
